modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="jhero"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="JU5E's Heroes"
description='''
A superhero addon for palladium!
'''

[[dependencies.jhero]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
